//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugaleMMORPGServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int CharacterID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public int ClassID { get; set; }
        public int Level { get; set; }
        public int Experience { get; set; }
        public int MapID { get; set; }
        public double Speed { get; set; }
        public double JumpSpeed { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Map Map { get; set; }
        public virtual User User { get; set; }
    }
}
