//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugaleMMORPGServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonsterType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonsterType()
        {
            this.Platforms = new HashSet<Platform>();
        }
    
        public int MonsterTypeID { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        public double Speed { get; set; }
        public double JumpSpeed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platform> Platforms { get; set; }
    }
}
