//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugaleMMORPGServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platform()
        {
            this.MonsterTypes = new HashSet<MonsterType>();
        }
    
        public int PlatformID { get; set; }
        public int MapID { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public double SizeX { get; set; }
        public double SizeY { get; set; }
        public double Location1X { get; set; }
        public double Location1Y { get; set; }
        public double Location2X { get; set; }
        public double Location2Y { get; set; }
    
        public virtual Map Map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonsterType> MonsterTypes { get; set; }
    }
}
