//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugaleMMORPGServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portal
    {
        public int PortalID { get; set; }
        public int MapID { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public int DestPortalID { get; set; }
    
        public virtual Map Map { get; set; }
    }
}
